import hashlib
import hmac
from datetime import timedelta
from app.config.settings import settings
from app.db.models.order import Order, OrderStatus
from app.db.models.payment import Payment, PaymentStatus
from app.db.models.print_job import PrintJob, PrintJobStatus
from app.db.models.print_server import PrintServer
from app.db.models.otp import OTP
from app.db.models.document import Document, DocumentStatus
from app.utils.crypto import generate_secure_otp, encrypt_value, decrypt_value, compute_file_sha256
from app.services.storage_service import storage_service
from app.utils.common import now, naive, fail, audit

def otp_digest(code, station):
    if not settings.OTP_HASH_KEY:
        raise RuntimeError('OTP_HASH_KEY is required')
    return hmac.new(settings.OTP_HASH_KEY.encode(), (station + ':' + code).encode(), hashlib.sha256).hexdigest()

class OTPService:
    def generate_and_store_otp(self, db, order_id):
        order = db.query(Order).filter_by(id=order_id).one()
        # Serialize allocation per station so active six-digit codes cannot collide.
        db.query(PrintServer).filter_by(id=order.print_server_id).with_for_update().populate_existing().one()
        existing = db.query(OTP).filter_by(order_id=order_id).first()
        if existing:
            if existing.active and not existing.used_at and naive(existing.expires_at) > now():
                return decrypt_value(existing.encrypted_value)
            fail('OTP_ALREADY_ISSUED', 'An OTP cannot be regenerated by replaying a payment.', 409)
        for _ in range(100):
            code = generate_secure_otp(6)
            digest = otp_digest(code, order.print_server_id)
            if not db.query(OTP).filter_by(otp_hash=digest, active=True).with_for_update().first(): break
        else:
            fail('OTP_UNAVAILABLE', 'Unable to allocate a release code.', 503)
        db.add(OTP(order_id=order_id, otp_hash=digest, encrypted_value=encrypt_value(code),
            expires_at=now() + timedelta(minutes=settings.OTP_TTL_MINUTES), active=True))
        db.flush()
        return code

    def get_otp_for_order(self, db, order_id):
        record = db.query(OTP).filter_by(order_id=order_id, active=True).first()
        if not record or record.used_at:
            fail('OTP_NOT_AVAILABLE', 'No unused release code is available.', 409)
        if naive(record.expires_at) <= now():
            fail('OTP_EXPIRED', 'Release code expired. Refund processing will follow.', 409)
        return decrypt_value(record.encrypted_value), record.expires_at

    def verify_and_release_job(self, db, server_id, plaintext_otp, order_id=None):
        if not server_id or len(plaintext_otp) != 6 or not plaintext_otp.isascii() or not plaintext_otp.isdigit():
            fail('INVALID_OTP', 'Invalid release code.')
        digest = otp_digest(plaintext_otp, server_id)
        query = db.query(OTP).join(Order, Order.id == OTP.order_id).filter(
            OTP.otp_hash == digest, OTP.active == True, Order.print_server_id == server_id)
        if order_id: query = query.filter(OTP.order_id == order_id)
        candidate = query.first()
        if not candidate:
            fail('INVALID_OTP', 'Invalid, expired or already used release code.')
        # Re-read under lock in a consistent order; the nonlocking lookup grants no permission.
        order = db.query(Order).filter_by(id=candidate.order_id).with_for_update().populate_existing().one()
        record = db.query(OTP).filter_by(id=candidate.id).with_for_update().populate_existing().one()
        payment = db.query(Payment).filter_by(order_id=order.id).with_for_update().populate_existing().first()
        job = db.query(PrintJob).filter_by(order_id=order.id, server_id=server_id).with_for_update().populate_existing().one()
        if (not record.active or record.used_at or naive(record.expires_at) <= now() or
                order.status != OrderStatus.WAITING_FOR_OTP or job.status != PrintJobStatus.QUEUED):
            fail('INVALID_OTP', 'Invalid, expired or already used release code.')
        if not payment or payment.status != PaymentStatus.CAPTURED or not payment.verified_at or payment.last_error:
            fail('PAYMENT_REQUIRED', 'A verified captured payment is required.', 409)
        doc = db.query(Document).filter_by(id=order.document_id).one()
        path = storage_service.resolve_storage_key(doc.storage_key)
        if (doc.status != DocumentStatus.ACTIVE or not path.is_file() or
                compute_file_sha256(str(path)) != doc.sha256):
            fail('DOCUMENT_INTEGRITY', 'Print-ready document is unavailable or has changed.', 409)
        record.active = False
        record.used_at = now()
        order.status = OrderStatus.RELEASED
        job.status = PrintJobStatus.RELEASED
        audit(db, 'OTP_RELEASED', order.id, actor='AGENT', station=server_id)
        db.commit()
        return job

otp_service = OTPService()
