# ==============================================================================
# Autonomous Self-Service Printing Platform - Build and Package Mobile APK (PowerShell)
# ==============================================================================
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$FrontendDir = Join-Path $ProjectRoot "frontend"
$DownloadsDir = Join-Path $ProjectRoot "downloads"
$StaticDir = Join-Path $ProjectRoot "print-agent\app\static"
$TunnelFile = Join-Path $ProjectRoot "storage\tunnel_url.txt"

# Ensure output target directories exist
if (-not (Test-Path $DownloadsDir)) { New-Item -ItemType Directory -Path $DownloadsDir -Force | Out-Null }
if (-not (Test-Path $StaticDir)) { New-Item -ItemType Directory -Path $StaticDir -Force | Out-Null }

$TunnelConfigFile = Join-Path $FrontendDir "lib\config\active_tunnel.dart"
$TunnelExampleFile = Join-Path $FrontendDir "lib\config\active_tunnel.dart.example"

if (Test-Path $TunnelFile) {
    $TunnelUrl = (Get-Content $TunnelFile -Raw).Trim()
    if ($TunnelUrl) {
        Write-Host "[i] Embedding active tunnel URL: $TunnelUrl" -ForegroundColor Gray
        "// Auto-generated by build-apk.ps1 - DO NOT EDIT DIRECTLY`nconst String kActiveTunnelUrl = '$TunnelUrl';`n" | Set-Content -Path $TunnelConfigFile -Encoding utf8
    }
}
if (-not (Test-Path -LiteralPath $TunnelConfigFile) -and (Test-Path -LiteralPath $TunnelExampleFile)) {
    Copy-Item -LiteralPath $TunnelExampleFile -Destination $TunnelConfigFile
}


Write-Host "[*] Building Android Release APK via Flutter..." -ForegroundColor Cyan
Push-Location $FrontendDir
try {
    flutter build apk --split-per-abi
} finally {
    Pop-Location
}

$Arm64Apk = Join-Path $FrontendDir "build\app\outputs\flutter-apk\app-arm64-v8a-release.apk"
$UniversalApk = Join-Path $FrontendDir "build\app\outputs\flutter-apk\app-release.apk"

$SourceApk = if (Test-Path $Arm64Apk) { $Arm64Apk } elseif (Test-Path $UniversalApk) { $UniversalApk } else { $null }

if ($SourceApk) {
    Write-Host "[*] Deploying APK to distribution targets..." -ForegroundColor Green
    Copy-Item -Path $SourceApk -Destination (Join-Path $DownloadsDir "autonomous-printer.apk") -Force
    Copy-Item -Path $SourceApk -Destination (Join-Path $StaticDir "autonomous-printer.apk") -Force

    $FileSize = (Get-Item (Join-Path $DownloadsDir "autonomous-printer.apk")).Length / 1MB
    $FormattedSize = "{0:N2} MB" -f $FileSize

    Write-Host "[✓] Release APK successfully built! ($FormattedSize)" -ForegroundColor Green
    Write-Host "    - $DownloadsDir\autonomous-printer.apk"
    Write-Host "    - $StaticDir\autonomous-printer.apk"
} else {
    Write-Host "[!] Build finished but output APK not found." -ForegroundColor Red
    exit 1
}
