// src/theme/colors.js
// Material Design 3 color palettes

export const lightColors = {
  primary:            '#6750A4',
  onPrimary:          '#FFFFFF',
  primaryContainer:   '#EADDFF',
  onPrimaryContainer: '#21005D',
  secondary:          '#625B71',
  onSecondary:        '#FFFFFF',
  secondaryContainer: '#E8DEF8',
  onSecondaryContainer:'#1D192B',
  surface:            '#FFFBFE',
  surfaceVariant:     '#E7E0EC',
  onSurface:          '#1C1B1F',
  onSurfaceVariant:   '#49454F',
  background:         '#FFFBFE',
  onBackground:       '#1C1B1F',
  error:              '#B3261E',
  errorContainer:     '#F9DEDC',
  onError:            '#FFFFFF',
  onErrorContainer:   '#410E0B',
  outline:            '#79747E',
  outlineVariant:     '#CAC4D0',
  success:            '#1B7A47',
  successContainer:   '#C8F5D8',
  warning:            '#7A5100',
  warningContainer:   '#FFDEA0',
  scrim:              'rgba(0,0,0,0.5)',
};

export const darkColors = {
  primary:            '#D0BCFF',
  onPrimary:          '#381E72',
  primaryContainer:   '#4F378B',
  onPrimaryContainer: '#EADDFF',
  secondary:          '#CCC2DC',
  onSecondary:        '#332D41',
  secondaryContainer: '#4A4458',
  onSecondaryContainer:'#E8DEF8',
  surface:            '#1C1B1F',
  surfaceVariant:     '#49454F',
  onSurface:          '#E6E1E5',
  onSurfaceVariant:   '#CAC4D0',
  background:         '#1C1B1F',
  onBackground:       '#E6E1E5',
  error:              '#F2B8B5',
  errorContainer:     '#8C1D18',
  onError:            '#601410',
  onErrorContainer:   '#F9DEDC',
  outline:            '#938F99',
  outlineVariant:     '#49454F',
  success:            '#6BDE9A',
  successContainer:   '#00522C',
  warning:            '#FFBA3A',
  warningContainer:   '#5F3D00',
  scrim:              'rgba(0,0,0,0.7)',
};
